import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import Providers from './providers';
import Image from 'next/image';
import Aside from './aside';
import Nav from './nav';
import Translation from './translation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <div className="wrap">
            <header className="global-header">
              <h1>
                <Image
                  className="dark:invert"
                  src="/next.svg"
                  alt="Next.js"
                  width={150}
                  height={30}
                  priority
                />
              </h1>
            </header>
            <div className="global-inner">
              <Aside>
                <Nav />
                <Translation />
              </Aside>
              <main className="global-main">{children}</main>
            </div>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
