import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';
import Providers from './providers';
import Image from 'next/image';
import Aside from './aside';
import Nav from './nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function LocaleLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className="antialiased">
        <Providers locale={locale}>
          <div className="wrap">
            <header className="global-header">
              <h1>
                <Image
                  className="dark:invert"
                  src="/next.svg"
                  alt="Next.js"
                  width={150}
                  height={30}
                  priority
                />
              </h1>
            </header>
            <div className="global-inner">
              <Aside>
                <Nav />
              </Aside>
              <main className="global-main">{children}</main>
            </div>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
